name = "runtheaiplay"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "runtheaiplay-db"
database_id = "9672e8ce-b9f4-4124-9af5-087e0f182080"
